"""atualizando tabela Auditoria

Revision ID: 040a1eeca1e6
Revises: 129cfc05d2e0
Create Date: 2026-05-03 22:14:00.050133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040a1eeca1e6'
down_revision: Union[str, Sequence[str], None] = '129cfc05d2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
