"""atualizando tabela Cliente

Revision ID: 129cfc05d2e0
Revises: 7b8861698aab
Create Date: 2026-05-03 22:09:59.043756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129cfc05d2e0'
down_revision: Union[str, Sequence[str], None] = '7b8861698aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_audit_acao', 'audit_log', ['acao'], unique=False)
    op.create_index('idx_audit_funcionario', 'audit_log', ['funcionario_id'], unique=False)
    op.create_index('idx_audit_registro', 'audit_log', ['tabela_afetada', 'registro_id'], unique=False)
    op.create_index('idx_audit_tabela', 'audit_log', ['tabela_afetada'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('idx_audit_usuario', 'audit_log', ['usuario_tipo', 'usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_usuario', table_name='audit_log')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_tabela', table_name='audit_log')
    op.drop_index('idx_audit_registro', table_name='audit_log')
    op.drop_index('idx_audit_funcionario', table_name='audit_log')
    op.drop_index('idx_audit_acao', table_name='audit_log')
    # ### end Alembic commands ###
