"""cria_tabelas_sistema

Revision ID: 13a33ef63c38
Revises: a05db4ce6772
Create Date: 2026-04-27 09:26:40.133058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13a33ef63c38'
down_revision: Union[str, Sequence[str], None] = 'a05db4ce6772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('documento', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cod_promocional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('desconto_percentual', sa.Float(), nullable=False),
    sa.Column('data_validade', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('combo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('imagem_link', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('tempo_preparo_medio', sa.Integer(), nullable=True),
    sa.Column('popular', sa.Boolean(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('data_contratacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('codigo_qr', sa.String(), nullable=True),
    sa.Column('qtd_lugares', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_qr'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('metodo_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_tipo', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('tabela_afetada', sa.String(), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('dados_anteriores', sa.JSON(), nullable=True),
    sa.Column('dados_novos', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_mesa', sa.Integer(), nullable=True),
    sa.Column('id_garcom', sa.Integer(), nullable=True),
    sa.Column('id_metodo_pagamento', sa.Integer(), nullable=False),
    sa.Column('id_cod_promocional', sa.Integer(), nullable=True),
    sa.Column('valor_a_pagar', sa.Float(), nullable=False),
    sa.Column('tipo_entrega', sa.String(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_finalizacao', sa.DateTime(), nullable=True),
    sa.Column('observacao_geral', sa.String(), nullable=True),
    sa.Column('preco_total', sa.Float(), nullable=False),
    sa.Column('desconto_aplicado', sa.Float(), nullable=False),
    sa.Column('taxa_entrega', sa.Float(), nullable=False),
    sa.Column('troco', sa.Float(), nullable=False),
    sa.Column('status_comanda', sa.String(), nullable=False),
    sa.Column('status_pagamento', sa.String(), nullable=False),
    sa.CheckConstraint('(id_cliente IS NOT NULL) OR (id_mesa IS NOT NULL)', name='check_cliente_ou_mesa'),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_cod_promocional'], ['cod_promocional.id'], ),
    sa.ForeignKeyConstraint(['id_garcom'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesa.id'], ),
    sa.ForeignKeyConstraint(['id_metodo_pagamento'], ['metodo_pagamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comanda_data', 'comanda', ['data_registro'], unique=False)
    op.create_index('idx_comanda_status', 'comanda', ['status_comanda'], unique=False)
    op.create_table('endereco_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('apelido', sa.String(), nullable=False),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('padrao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_cliente', 'padrao', name='unique_padrao_por_cliente')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('imagem_link', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('tempo_preparo_medio', sa.Integer(), nullable=True),
    sa.Column('popular', sa.Boolean(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_produto',
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combo_id'], ['combo.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('combo_id', 'produto_id')
    )
    op.create_table('pedido_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.Column('id_combo', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.CheckConstraint('(id_produto IS NOT NULL) <> (id_combo IS NOT NULL)', name='check_produto_ou_combo'),
    sa.ForeignKeyConstraint(['id_comanda'], ['comanda.id'], ),
    sa.ForeignKeyConstraint(['id_combo'], ['combo.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_comanda_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('status_anterior', sa.String(), nullable=True),
    sa.Column('status_novo', sa.String(), nullable=False),
    sa.Column('alterado_por_tipo', sa.String(), nullable=False),
    sa.Column('alterado_por_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_comanda'], ['comanda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco_num_residencia', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco_rua', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco_bairro', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco_cidade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco_complemento', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('status_comanda_log')
    op.drop_table('pedido_item')
    op.drop_table('combo_produto')
    op.drop_table('produto')
    op.drop_table('endereco_cliente')
    op.drop_index('idx_comanda_status', table_name='comanda')
    op.drop_index('idx_comanda_data', table_name='comanda')
    op.drop_table('comanda')
    op.drop_table('audit_log')
    op.drop_table('metodo_pagamento')
    op.drop_table('mesa')
    op.drop_table('funcionario')
    op.drop_table('combo')
    op.drop_table('cod_promocional')
    op.drop_table('cliente')
    op.drop_table('categoria_produto')
    # ### end Alembic commands ###
