"""create initial tables

Revision ID: 59e46e006efa
Revises: 
Create Date: 2025-08-11 12:08:22.149033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e46e006efa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('endereco_num_residencia', sa.String(), nullable=False),
    sa.Column('endereco_rua', sa.String(), nullable=False),
    sa.Column('endereco_bairro', sa.String(), nullable=False),
    sa.Column('endereco_cidade', sa.String(), nullable=False),
    sa.Column('endereco_complemento', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
