"""atualizando tabela Funcionario

Revision ID: 646404b0c9ec
Revises: 7ae0384eb33a
Create Date: 2026-05-03 22:58:18.449260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646404b0c9ec'
down_revision: Union[str, Sequence[str], None] = '7ae0384eb33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
