"""create initial tables 2

Revision ID: a05db4ce6772
Revises: 5226554a93e6
Create Date: 2025-08-11 12:26:00.947238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a05db4ce6772'
down_revision: Union[str, Sequence[str], None] = '5226554a93e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('endereco_num_residencia', sa.String(), nullable=False),
    sa.Column('endereco_rua', sa.String(), nullable=False),
    sa.Column('endereco_bairro', sa.String(), nullable=False),
    sa.Column('endereco_cidade', sa.String(), nullable=False),
    sa.Column('endereco_complemento', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco_num_residencia', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco_rua', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco_bairro', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco_cidade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco_complemento', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Users_pkey')),
    sa.UniqueConstraint('email', name=op.f('Users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('users')
    # ### end Alembic commands ###
